### ISSUE TITLE
Toggling options will reset the UI to English

### ISSUE THREAD

**Issue by williamsp** [liyasthomas/postwoman#417]
**Describe the bug**
Toggling options will reset the UI to English.

**To Reproduce**
1. Go to 'https://postwoman.io/'
1. Click on 'Choose Language' on lower right corner
1. Click on 'Bahasa Indonesia'
1. Switch on the 'Sertakan di URL' toggle on Authentication tab
1. The UI resets to English

**Expected behavior**
The UI still in Bahasa Indonesia.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 72

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by liyasthomas** [comment]
Issue has been identified. Will fix it ASAP

**Comment by runyasak** [comment]
I have fixed by set `detectBrowserLanguage` to false.
It will disable cookie and enable for redirect.
Ref: https://nuxt-community.github.io/nuxt-i18n/browser-language-detection.html

You can review on my PR #418. 
If you have any feedback or suggestion, you can tell me. 😁

**Comment by liyasthomas** [comment]
#418 doesn't seem to fix this issue. Preview build for #418 : https://deploy-preview-418--postwoman.netlify.com/
On `pages/index.vue` @line `1850`, `this.$router.replace` cause this bug.

**Comment by williamsp** [comment]
It seems that e2d7c02 only fix the toggle on the Home page.
But other toggles (like Multicolor and Proxy in Settings page) still have this issue.

**Comment by liyasthomas** [comment]
Will fix it ASAP.

**Comment by liyasthomas** [comment]
Fixed in https://github.com/liyasthomas/postwoman/commit/945a83625d6e902d61955b58cd17f322a9b0159a
