### ISSUE TITLE
Currently completely broken

### ISSUE THREAD

**Issue by levrik** [liyasthomas/postwoman#980]
**Describe the bug**

I can't see the response body of any request.
It shows the status correctly but the body is empty.
The developer console is showing this:

![image](https://user-images.githubusercontent.com/9491603/86602399-e3762780-bfa2-11ea-96f6-be96b164f6bf.png)

**To Reproduce**

1. Just send a request
2. It shows that the request succeeded with the correct status code but no body. `content-length` is correctly shown.

**Expected behavior**

To show the response body or at least an error that something went wrong.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome 83.0.4103.116 
 - Version v1.9.7

This is quite annoying right now because Postwoman is my main tool and I have to set up a different tool now to be able to continue to work.

**Comment by liyasthomas** [comment]
Possible duplicate of #764 , #979 
Try this: https://github.com/liyasthomas/postwoman/issues/764#issuecomment-654096293

or this:

https://github.com/liyasthomas/postwoman/issues/764#issuecomment-654106079

**Comment by levrik** [comment]
@liyasthomas Sadly I'm not allowed to use the proxy for data security reasons. Looks I'm gonna have to wait for the fix in the extension to get published. Will switch back to Postman in the meantime to get my work done.

**Comment by liyasthomas** [comment]
You can try in another browser (ex: Firefox).

**Comment by levrik** [comment]
@liyasthomas Already got my work done with Postman now (although their GraphQL support sucks...)
Will try Postwoman in Firefox the next time if the Chrome extension wasn't updated until then.

**Comment by AndrewBastin** [comment]
@levrik really sorry about the inconvenience. But we kinda hit a snag with the Chrome Web Store, they are kinda having troubles reviewing extension updates these days due to the whole global situation. I am getting in touch with the Chrome Web Store Dev Support to get it fixed.

**Comment by liyasthomas** [comment]
Fixed in latest release of [Chrome extension v0.13](https://chrome.google.com/webstore/detail/postwoman-browser-extensi/amknoiejhlmhancpahfcfcfhllgkpbld).
Extension should update automatically on Chrome, if not do manual update form `chrome://extensions`.

**Comment by levrik** [comment]
@liyasthomas @AndrewBastin The error from this ticket is gone with `0.13` of the extension. But it's still broken. Loading bar is shown endlessly, developer console shows the following.
![image](https://user-images.githubusercontent.com/9491603/87642087-57ee5a80-c749-11ea-93c4-fa5b144a40a1.png)

**Comment by liyasthomas** [comment]
Can you try again after a force refresh <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>R</kbd>

**Comment by levrik** [comment]
@liyasthomas Already tried this. Didn't help.
